export const features = [
  {
    id: 1,
    image: "./feature/bookcase.png",
    name: "bookcase",
    price: 599,
    star: "⭐⭐⭐⭐",
  },
  {
    id: 2,
    image: "./feature/chests.png",
    name: "chests",
    price: 599,
    star: "⭐⭐⭐⭐",
  },
  {
    id: 3,
    image: "./feature/diningchair.png",
    name: "dining chair",
    price: 599,
    star: "⭐⭐⭐⭐",
  },
  {
    id: 4,
    image: "./feature/hammock.png",
    name: "hammock",
    price: 599,
    star: "⭐⭐⭐⭐",
  },
  {
    id: 5,
    image: "./feature/hatstand.png",
    name: "hatstand",
    price: 599,
    star: "⭐⭐⭐⭐",
  },
  {
    id: 6,
    image: "./feature/mattresses.png",
    name: "mattresses",
    price: 599,
    star: "⭐⭐⭐⭐",
  },
  {
    id: 7,
    image: "./feature/nightstand.png",
    name: "nightstand",
    price: 599,
    star: "⭐⭐⭐⭐",
  },
  {
    id: 8,
    image: "./feature/ottoman.png",
    name: "ottoman",
    price: 599,
    star: "⭐⭐⭐⭐",
  },
  {
    id: 9,
    image: "./feature/pillows.png",
    name: "pillows",
    price: 599,
    star: "⭐⭐⭐⭐",
  },
  {
    id: 10,
    image: "./feature/wallclock.png",
    name: "wall clock",
    price: 599,
    star: "⭐⭐⭐⭐",
  },
];
