export const features = [
  {
    id: 1,
    category: "livingroom",
    image: "./images/livingroom/ezeck-tv-cabinet.jpg",
    name: "ezeck tv cabinet",
    price: 599,
  },
  {
    id: 2,
    category: "livingroom",
    image: "./images/livingroom/osmund-ottoman.jpg",
    name: "osmund ottoman",
    price: 599,
  },
  {
    id: 3,
    category: "livingroom",
    image: "./images/livingroom/sterling-recliner-sofa.jpg",
    name: "sterling recliner sofa",
    price: 599,
  },
  {
    id: 4,
    category: "livingroom",
    image: "./images/livingroom/teemo-side-table.jpg",
    name: "teemo sidetable",
    price: 599,
  },
  {
    id: 5,
    category: "bedroom",
    image: "./images/bedroom/belaine.jpg",
    name: "belaine bed",
    price: 599,
  },
  {
    id: 6,
    category: "bedroom",
    image: "./images/bedroom/braxton.jpg",
    name: "braxton bed",
    price: 599,
  },
  {
    id: 7,
    category: "bedroom",
    image: "./images/bedroom/ryland-standing-dresser.jpg",
    name: "ryland standing dresser",
    price: 599,
  },
  {
    id: 8,
    category: "bedroom",
    image: "./images/bedroom/seth-sofa-bed.jpg",
    name: "seth sofa bed",
    price: 599,
  },
  {
    id: 9,
    category: "bedroom",
    image: "./images/bedroom/nina-bed-side.jpg",
    name: "nina bed side",
    price: 599,
  },
  {
    id: 10,
    category: "bedroom",
    image: "./images/bedroom/winzel-closed.jpg",
    name: "winzel closed",
    price: 599,
  },
  {
    id: 11,
    category: "officeroom",
    image: "./images/officeroom/chandler-adjustable-desk.jpg",
    name: "chandler adjustable desk",
    price: 599,
  },
  {
    id: 12,
    category: "officeroom",
    image: "./images/officeroom/cole-multifunction-study-desk.jpg",
    name: "cole multifunction study desk",
    price: 599,
  },
  {
    id: 13,
    category: "officeroom",
    image: "./images/officeroom/fedora-office-chair.jpg",
    name: "fedora office chair",
    price: 599,
  },
  {
    id: 14,
    category: "officeroom",
    image: "./images/officeroom/felix-executive-chair.jpg",
    name: "felix executive chair",
    price: 599,
  },
  {
    id: 15,
    category: "officeroom",
    image: "./images/officeroom/Frankie-ergonomic-chair.jpg",
    name: "Frankie ergonomic chair",
    price: 599,
  },
  {
    id: 16,
    category: "officeroom",
    image: "./images/officeroom/tilly-featured.png",
    name: "tilly featured",
    price: 599,
  },
  {
    id: 17,
    category: "kitchenroom",
    image: "./images/kitchen/damiana-dining-set.jpg",
    name: "damiana dining set",
    price: 599,
  },
  {
    id: 18,
    category: "kitchenroom",
    image: "./images/kitchen/damien-minipub-set.jpg",
    name: "damien minipub set",
    price: 599,
  },
  {
    id: 19,
    category: "kitchenroom",
    image: "./images/kitchen/darrel-dining-set.jpg",
    name: "darrel dining set",
    price: 599,
  },
  {
    id: 20,
    category: "kitchenroom",
    image: "./images/kitchen/deidra-dining-set.jpg",
    name: "deidra dining set",
    price: 599,
  },
  {
    id: 21,
    category: "kitchenroom",
    image: "./images/kitchen/kyrie-kitchen-table.jpg",
    name: "kyrie kitchen table",
    price: 599,
  },
  {
    id: 22,
    category: "storageroom",
    image: "./images/storage/acadia-square-box.jpg",
    name: "acadia square box",
    price: 599,
  },
  {
    id: 23,
    category: "storageroom",
    image: "./images/storage/alexis-basket-set.jpg",
    name: "alexis basket set",
    price: 599,
  },
  {
    id: 24,
    category: "storageroom",
    image: "./images/storage/raizen-divider.jpg",
    name: "raizen divider",
    price: 599,
  },
  {
    id: 25,
    category: "storageroom",
    image: "./images/storage/ralston-multipurpose-rack.jpg",
    name: "ralston multipurpose rack",
    price: 599,
  },
  {
    id: 26,
    category: "storageroom",
    image: "./images/storage/rohan-shoe-cabinet.jpg",
    name: "rohan shoe cabinet",
    price: 599,
  },
  {
    id: 27,
    category: "benches",
    image: "./images/benches/octavia-accent-chair.jpg",
    name: "octavia accent chair",
    price: 599,
  },

  {
    id: 28,
    category: "benches",
    image: "./images/benches/orene-accent-chair.jpg",
    name: "orene accent chair",
    price: 599,
  },
  {
    id: 29,
    category: "benches",
    image: "./images/benches/orton-stool.jpg",
    name: "orton stool",
    price: 599,
  },
  {
    id: 30,
    category: "benches",
    image: "./images/benches/sebastian-cosmo-grey.jpg",
    name: "sebastian cosmo grey",
    price: 599,
  },
];
